/**
 * Action: object avec une clé type et eventuellement un payload.
 */

export const ActionTypes = {
  USER_LIST_REQUEST: 'USER_LIST_REQUEST',
  USER_LIST_UPDATE: 'USER_LIST_UPDATE',

  USER_CONNECTION_REQUEST: 'USER_CONNECTION_REQUEST',
  USER_CONNECTION_SUCCESS: 'USER_CONNECTION_SUCCESS',
  USER_CONNECTION_FAILURE: 'USER_CONNECTION_FAILURE',

  USER_LOGOUT: 'USER_LOGOUT',

  MESSAGE_LIST_REQUEST: 'MESSAGE_LIST_REQUEST',
  MESSAGE_LIST_UPDATE: 'MESSAGE_LIST_UPDATE',

  MESSAGE_CONNECTION_REQUEST: 'MESSAGE_CONNECTION_REQUEST',
  MESSAGE_CONNECTION_SUCCESS: 'MESSAGE_CONNECTION_SUCCESS',
  MESSAGE_CONNECTION_FAILURE: 'MESSAGE_CONNECTION_FAILURE',

  NOTIFICATION_UPDATE: 'NOTIFICATION_UPDATE',
  ERROR_UPDATE: 'ERROR_UPDATE',
  ONLINE_STATUS_UPDATE: 'ONLINE_STATUS_UPDATE',
};